---
- name: Deploy MERN to Kubernetes
  hosts: web
  become: yes

  tasks:

    - name: Copy k8s manifests to EC2
      copy:
        src: ../k8s/
        dest: /home/ubuntu/k8s/
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Apply Namespace
      become_user: ubuntu
      shell: kubectl apply -f /home/ubuntu/k8s/namespace.yaml

    - name: Apply Secret
      become_user: ubuntu
      shell: kubectl apply -f /home/ubuntu/k8s/secret.yaml

    - name: Apply Backend
      become_user: ubuntu
      shell: |
        kubectl apply -f /home/ubuntu/k8s/backend-deployment.yaml
        kubectl apply -f /home/ubuntu/k8s/backend-service.yaml

    - name: Apply Frontend
      become_user: ubuntu
      shell: |
        kubectl apply -f /home/ubuntu/k8s/frontend-deployment.yaml
        kubectl apply -f /home/ubuntu/k8s/frontend-service.yaml
    
    - name: Render ingress
      template:
        src: ../k8s/ingress.yaml.j2
        dest: /home/ubuntu/k8s/ingress.yaml

    - name: Apply Ingress
      become_user: ubuntu
      shell: kubectl apply -f /home/ubuntu/k8s/ingress.yaml